apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    tag: hw
spec:
  containers:
  - name: echoserver2
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
      - containerPort: 8080
        name: http-echo

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    tag: hw
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 1080
    targetPort: http-echo
