apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-init
  labels:
    app: hwinit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwinit
  template:
    metadata:
      labels:
        app: hwinit
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]