apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    app: hwdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hwdeploy
  template:
    metadata:
      labels:
        app: hwdeploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "1080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1080

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: hwdeploy
  ports:
  - name: nginx-port
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: multitool-port
    protocol: TCP
    port: 1080
    targetPort: 1080

---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: testmultitool
    image: wbitt/network-multitool:latest
    env:
        - name: HTTP_PORT
          value: "2080"
    ports:
      - containerPort: 2080
