apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    app: hwdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwdeploy
  template:
    metadata:
      labels:
        app: hwdeploy
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'while true; do echo "Current time is $(date)" >> /output/file.log; sleep 5; done']
        volumeMounts:
        - mountPath: /output
          name: localvol
      - name: multitool
        image: wbitt/network-multitool:latest
        volumeMounts:
        - mountPath: /input
          name: localvol
      volumes:
      - name: localvol
        persistentVolumeClaim:
          claimName: pvc-test
