apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: hwdeploy
  ports:
  - name: nginx-port
    protocol: TCP
    port: 9001
    targetPort: 80
    nodePort: 30080
  - name: multitool-port
    protocol: TCP
    port: 9002
    targetPort: 8080
    nodePort: 30880